//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class CuisineType
    {
        public CuisineType()
        {
            this.Recipes = new HashSet<Recipe>();
        }
    
        [DisplayName("Cuisine")]
        public string Name { get; set; }
        [DisplayName("Cuisine")]
        public int CuisineTypeId { get; set; }
    
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
