//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.RecipeIngredients = new HashSet<RecipeIngredient>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int RecipeCatId { get; set; }

        [DisplayName ("Description")]
        public string RecipeDescription { get; set; }

        [DisplayName("Active Prep Time")]
        public int PrepTime { get; set; }

        [DisplayName("Inactive Cook Time")]
        public int CookTime { get; set; }
        public string Procedures { get; set; }
        public int CuisineTypeId { get; set; }
    
        public virtual RecipeCategory RecipeCategory { get; set; }
        public virtual ICollection<RecipeIngredient> RecipeIngredients { get; set; }
        public virtual CuisineType CuisineType { get; set; }
    }
}
