//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class RecipeCategory
    {
        public RecipeCategory()
        {
            this.Recipes = new HashSet<Recipe>();
        }
    
        public int Id { get; set; }

        [DisplayName("Category")]
        public string CatName { get; set; }
        public string CatDesc { get; set; }
    
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
